name: Check latest uuu version
on:
  schedule:
    - cron:  '0 13 * * *'
  push:
    branches:
      - 'master'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - 'master'
    paths-ignore:
      - '**.md'

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check version
        run: |
          read LATEST_UUU_RELEASE_NAME LATEST_UUU_RELEASE_TAG_NAME < <(echo $(curl -s "https://api.github.com/repos/NXPMicro/mfgtools/releases/latest" | jq -r '.name, .tag_name'))
          read LATEST_DOCKER_UUU_RELEASE_NAME LATEST_DOCKER_UUU_RELEASE_TAG_NAME < <(echo $(curl -s "https://api.github.com/repos/nosidewen/docker-uuu/releases/latest" | jq -r '.name, .tag_name'))

          echo "LATEST_UUU_RELEASE_NAME: $LATEST_UUU_RELEASE_NAME"
          echo "LATEST_UUU_RELEASE_TAG_NAME: $LATEST_UUU_RELEASE_TAG_NAME"

          echo "LATEST_DOCKER_UUU_RELEASE_NAME: $LATEST_DOCKER_UUU_RELEASE_NAME"
          echo "LATEST_DOCKER_UUU_RELEASE_TAG_NAME: $LATEST_DOCKER_UUU_RELEASE_TAG_NAME"

          if [ "$LATEST_UUU_RELEASE_TAG_NAME" = "$LATEST_DOCKER_UUU_RELEASE_TAG_NAME" ]; then
            echo "No new uuu version found in NXPMicro/mfgtools."
          else
            echo "New uuu version found in NXPMicro/mfgtools."
            echo "Trigger repository_dispatch: latest-uuu-version in nosidewen/docker-uuu"
            curl -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN_REPO_SCOPE }}" \
                 -H "Content-Type: application/json" \
                 -H 'Accept: application/vnd.github.everest-preview+json' \
                 --request POST \
                 --data '{"event_type": "latest-uuu-version", "client_payload": {"tag_name": "'"$LATEST_UUU_RELEASE_TAG_NAME"'", "name": "'"$LATEST_UUU_RELEASE_NAME"'"}}' \
                 -s \
                 "https://api.github.com/repos/nosidewen/docker-uuu/dispatches"
          fi